package com.chattrix.api.requests;

import com.chattrix.api.entities.CallType;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

/**
 * Request DTO for initiating a new call.
 * Note: callId and channelId are generated by the server, not provided by the client.
 * Validates: Requirements 1.1, 3.1
 */
@Getter
@Setter
public class InitiateCallRequest {
    
    @NotBlank(message = "Callee ID cannot be blank")
    private String calleeId;
    
    @NotNull(message = "Call type cannot be null")
    private CallType callType;
}
